/* =====================================================================
   Coach  --  tactics/calculation exercises built from your real games.

   Data comes from window.EXERCISES (generated by build/build_exercises.py
   out of your chess.com history). Everything here is optional: if
   exercises.js is missing the app runs exactly as it did before.

   A puzzle uses the SAME card shape as an opening line -- a start position
   plus a list of move-edges -- so the trainer engine in app.js plays both
   through one code path. The only additions are `startFen` (openings always
   began from the initial position) and `blind` (calculation mode).

   Loaded BEFORE app.js: it only defines things here, and is called later.
   ===================================================================== */
'use strict';

const EXDATA = window.EXERCISES || null;
const PACKS = EXDATA ? EXDATA.packs : [];
const COACH_PROFILE = EXDATA ? EXDATA.profile : null;

/* ---------------- puzzle cards ---------------- */
const PUZZLES = [];
const PUZZLE_BY_ID = {};
const PUZZLES_BY_PACK = {};
(function enumeratePuzzles(){
  for(const pack of PACKS){
    PUZZLES_BY_PACK[pack.id] = [];
    for(const item of pack.items){
      const card = {
        id: `${pack.id}#${item.id}`,
        isPuzzle: true,
        packId: pack.id,
        courseName: pack.name,
        name: (item.meta && item.meta.title) || pack.name,
        color: item.color,
        startFen: item.startFen,
        edges: item.edges,
        myMoves: item.myMoves,
        blind: !!pack.blind,
        meta: item.meta || {},
      };
      PUZZLES.push(card);
      PUZZLE_BY_ID[card.id] = card;
      PUZZLES_BY_PACK[pack.id].push(card);
    }
  }
})();
const packById = id => PACKS.find(p => p.id === id);
const hasCoach = () => PUZZLES.length > 0;

/* =====================================================================
   LESSONS  --  spaced repetition on the SKILL, not on the position.

   The packs above schedule POSITIONS: card 47 comes back on day 9, then
   day 23, forever. That is right for an opening move and wrong for a
   tactic. Once you have solved "you hung the knight on f6 in that game"
   twice, seeing it again tests whether you remember that board, not
   whether you would spot the pattern in a new one.

   So a lesson is the unit here. The lesson has a due date; when it comes
   up you get FRESH positions from its pool at your current rung. Your own
   two positions open the lesson and then retire (meta.maxReps). Solve
   enough cleanly at a rung and you move up to harder material, which is
   the "just past what you can already do" part of deliberate practice.
   Get it wrong repeatedly and you drop back a rung rather than grinding.
   ===================================================================== */

const LESSONS = (EXDATA && EXDATA.lessons) ? EXDATA.lessons : [];
const LESSON_BY_ID = {};
const LESSON_CARDS = [];
const LESSON_CARD_BY_ID = {};
(function enumerateLessons(){
  for(const L of LESSONS){
    LESSON_BY_ID[L.id] = L;
    L.stageById = {};
    for(const st of L.stages){
      L.stageById[st.id] = st;
      st.cardObjs = [];
      for(const item of st.cards){
        // the build already emits ids prefixed L-<lesson>-<rung>, so they are
        // unique and stable across rebuilds -- which keeps your history valid
        const card = {
          id: item.id, isPuzzle: true, isLesson: true,
          lessonId: L.id, stageId: st.id, packId: 'lesson-' + L.id,
          courseName: L.title, name: (item.meta && item.meta.title) || st.name,
          color: item.color, startFen: item.startFen, edges: item.edges,
          myMoves: item.myMoves, meta: item.meta || {},
        };
        st.cardObjs.push(card);
        LESSON_CARDS.push(card);
        LESSON_CARD_BY_ID[card.id] = card;
      }
    }
  }
})();
const hasLessons = () => LESSONS.length > 0;

// Clean solves needed at a rung before you move up. Your own positions only
// need to be seen; the graded rungs need a real run of them.
const RUNG_TARGET = {own: 2, warmup: 4, level: 6, stretch: 5};
// Below this accuracy at a rung, the rung is too hard -- step back down.
const RUNG_FLOOR = 0.5;
const RUNG_MIN_TRIES = 6;

function lessonSrs(id){
  let s = state.lessons[id];
  if(!s){
    s = state.lessons[id] = {rung:0, clean:0, tries:0, reps:0, lapses:0,
                             interval:0, due:today(), seen:false, mastered:false};
  }
  return s;
}
function lessonState(id){
  const s = state.lessons[id];
  if(!s || !s.seen) return 'new';
  return s.due <= today() ? 'due' : 'learning';
}
function lessonStage(L){
  const s = lessonSrs(L.id);
  return L.stages[Math.min(s.rung, L.stages.length - 1)];
}
function lessonProgress(L){
  const s = lessonSrs(L.id);
  const target = RUNG_TARGET[lessonStage(L).id] || 5;
  const rungPct = Math.min(1, s.clean / target);
  const pct = (s.rung + rungPct) / L.stages.length;
  return {pct: Math.round(pct * 100), rung: s.rung, clean: s.clean,
          target, mastered: s.mastered};
}

// Which lesson to spend today on. Costliest-first, but a lesson you have
// already started outranks one you have not, so you finish what you begin.
function lessonPriority(L){
  const s = lessonSrs(L.id);
  const cost = (L.evidence && L.evidence.cpLost) || 0;
  const started = s.seen ? 1.35 : 1.0;
  const overdue = Math.max(0, today() - s.due);
  return cost * started + overdue * 500;
}

/* Record one solved lesson card and move the rung if earned. */
function creditLesson(card, solvedClean){
  const L = LESSON_BY_ID[card.lessonId];
  if(!L) return;
  const s = lessonSrs(L.id);
  s.seen = true;
  s.tries++;
  if(solvedClean) s.clean++; else s.clean = Math.max(0, s.clean - 1);

  const stage = lessonStage(L);
  const target = RUNG_TARGET[stage.id] || 5;

  if(s.clean >= target){
    if(s.rung < L.stages.length - 1){
      s.rung++; s.clean = 0; s.tries = 0;
      toast(`Lesson up a level: ${L.stages[s.rung].name}`, 'good');
    }else{
      s.mastered = true;
      toast(`Lesson mastered: ${L.title}`, 'good');
    }
  }else if(s.tries >= RUNG_MIN_TRIES && (s.clean / s.tries) < RUNG_FLOOR && s.rung > 0){
    s.rung--; s.clean = 0; s.tries = 0;
    toast('Dropping back a level — this one needs more reps.', '');
  }

  // When the lesson comes back. Mastered lessons go into slow maintenance
  // rather than disappearing, because the pattern still has to stay sharp.
  s.reps++;
  if(solvedClean){
    s.interval = s.mastered ? Math.min(45, Math.max(14, (s.interval||7)*2))
                            : (s.reps <= 1 ? 1 : Math.min(14, Math.round((s.interval||1)*2)));
  }else{
    s.lapses++;
    s.interval = 1;
  }
  s.due = today() + s.interval;
  save();
}

/* Fresh cards from a lesson: never one you have already solved. */
function freshFromLesson(L, n){
  const out = [];
  const start = lessonSrs(L.id).rung;
  // current rung first, then spill into the next one if this rung is used up
  for(let i = start; i < L.stages.length && out.length < n; i++){
    for(const c of L.stages[i].cardObjs){
      if(out.length >= n) break;
      if(cardState(c.id) === 'new') out.push(c);
    }
  }
  // every position in the pool has been solved -- fall back to the ones due
  // for review, oldest first
  if(out.length < n){
    const due = L.stages.flatMap(st => st.cardObjs)
      .filter(c => cardState(c.id) === 'due')
      .sort((a, b) => srs(a.id).due - srs(b.id).due);
    for(const c of due){ if(out.length >= n) break; out.push(c); }
  }
  return out;
}


/* ---------------- adaptive difficulty ----------------
   Puzzles are bundled across a wide rating band and the app picks within it,
   so a bad initial guess at your level corrects itself in a few sessions
   instead of needing the whole set rebuilt. Standard Elo both ways: you rate
   the puzzle, the puzzle rates you. */
function puzzleRating(){
  if(state.profile.puzzleRating) return state.profile.puzzleRating;
  const band = COACH_PROFILE && COACH_PROFILE.puzzleBand;
  return (band && band.centre) || 900;
}
function updatePuzzleRating(card, solvedClean){
  const target = card.meta && card.meta.rating;
  if(!target) return;                       // own-game cards carry no rating
  const mine = puzzleRating();
  const expected = 1/(1+Math.pow(10,(target-mine)/400));
  const K = state.profile.puzzlesDone < 30 ? 40 : 20;   // settle in faster at first
  state.profile.puzzleRating = Math.round(mine + K*((solvedClean?1:0)-expected));
  state.profile.puzzlesDone = (state.profile.puzzlesDone||0)+1;
}

/* ---------------- daily tactics queue ----------------
   Order of claims on the budget:
     1. positions genuinely due for review that have not retired,
        capped at half so review can never crowd out new learning;
     2. today's lessons -- and only TWO of them, not all six. Spreading
        six patterns thinly across six puzzles a day is how you end up
        vaguely familiar with everything and good at nothing; deliberate
        practice wants concentration;
     3. whatever else is unseen, nearest your level, if there is room.       */

function allTacticCards(){ return PUZZLES.concat(LESSON_CARDS); }

// How many lessons to work in one sitting.
const LESSON_FOCUS = 2;

function buildTacticsQueue(budget){
  if(budget <= 0 || (!hasCoach() && !hasLessons())) return [];
  const out = [];
  const seen = new Set();
  const add = c => { if(!seen.has(c.id)){ seen.add(c.id); out.push(c); } };

  // 1. due reviews (retired cards are not 'due', so they never appear)
  const due = allTacticCards().filter(c => cardState(c.id) === 'due')
                              .sort((a, b) => srs(a.id).due - srs(b.id).due);
  due.slice(0, Math.ceil(budget / 2)).forEach(add);

  // 2. today's lessons
  const active = LESSONS
    .filter(L => lessonState(L.id) !== 'learning' && !allRungsExhausted(L))
    .sort((a, b) => lessonPriority(b) - lessonPriority(a))
    .slice(0, LESSON_FOCUS);
  if(active.length){
    const share = Math.max(1, Math.floor((budget - out.length) / active.length));
    for(const L of active) freshFromLesson(L, share).forEach(add);
  }

  // 3. top up from the packs built out of your own games
  if(out.length < budget){
    const mine = puzzleRating();
    PUZZLES.filter(c => cardState(c.id) === 'new')
      .sort((a, b) => Math.abs((a.meta.rating || mine) - mine)
                    - Math.abs((b.meta.rating || mine) - mine))
      .slice(0, budget - out.length).forEach(add);
  }
  return out.slice(0, budget);
}

function allRungsExhausted(L){
  return L.stages.every(st => st.cardObjs.every(c => {
    const s = cardState(c.id);
    return s !== 'new' && s !== 'due';
  }));
}

function lessonsDue(){
  return LESSONS.filter(L => lessonState(L.id) !== 'learning'
                          && !allRungsExhausted(L)).length;
}

function tacticsDue(){ return PUZZLES.filter(c=>cardState(c.id)==='due').length; }
function tacticsNew(){ return PUZZLES.filter(c=>cardState(c.id)==='new').length; }
function tacticsSolved(){ return PUZZLES.filter(c=>cardState(c.id)!=='new').length; }

/* ---------------- per-card context shown during training ---------------- */
// Evaluations are clamped at ±10 pawns before differencing, so the worst
// mistakes all come out at exactly "20 pawns" — a number that means "winning
// to losing", not a literal material count. Say that instead of printing it.
function lossPhrase(cp){
  if(cp>=1500) return 'it threw the game away';
  if(cp>=900)  return 'it turned a winning position into a losing one';
  if(cp>=400)  return `it cost you about ${Math.round(cp/100)} pawns`;
  return `it cost you about ${(cp/100).toFixed(1)} pawns`;
}

// Evals are clamped at +/-10 pawns before differencing, so every really bad
// move comes out at exactly "20.0" -- printing that three times in a row looks
// broken and says nothing. Say what happened instead.
function costLabel(cp){
  if(cp == null) return '';
  if(cp >= 1500) return 'lost the game';
  if(cp >= 900)  return 'winning → losing';
  if(cp >= 400)  return `−${Math.round(cp/100)} pawns`;
  return `−${(cp/100).toFixed(1)}`;
}

function puzzlePrompt(card){
  const m = card.meta||{};
  switch(m.kind){
    case 'own':    return `You played ${m.played} here and ${lossPhrase(m.cpLoss)}. Find the move you missed.`;
    case 'punish': return `Your opponent just played ${m.oppMove}. Punish it.`;
    case 'refute': return `You just played ${m.played}. Now play your opponent's side and show why it loses.`;
    case 'calc':   return `Calculate the whole line before you move — the board will not update.`;
    case 'endgame':return `Find the winning technique.`;
    case 'lesson': return `Find the best move.`;
    default:       return `Find the best move.`;
  }
}
function puzzleSubtitle(card){
  const m = card.meta||{};
  const bits = [];
  if(m.rating) bits.push(`rated ${m.rating}`);
  if(m.moveNumber) bits.push(`move ${m.moveNumber}`);
  if(m.timeClass) bits.push(m.timeClass);
  if(m.endTime) bits.push(new Date(m.endTime*1000).toLocaleDateString());
  if(m.themes && m.themes.length) bits.push(m.themes.slice(0,3).map(themeLabel).join(', '));
  return bits.join(' · ');
}
const THEME_LABELS = {
  hangingPiece:'hanging piece', fork:'fork', pin:'pin', skewer:'skewer',
  discoveredAttack:'discovered attack', backRankMate:'back rank',
  mateIn1:'mate in 1', mateIn2:'mate in 2', mateIn3:'mate in 3',
  trappedPiece:'trapped piece', promotion:'promotion',
  capturingDefender:'removing the defender', advancedPawn:'passed pawn',
  crushing:'winning material', advantage:'advantage', short:'short', long:'long',
  sacrifice:'sacrifice', deflection:'deflection', attraction:'attraction',
  quietMove:'quiet move', defensiveMove:'defensive move', intermezzo:'in-between move',
  doubleCheck:'double check', xRayAttack:'x-ray', interference:'interference',
  clearance:'clearance', zugzwang:'zugzwang', mate:'checkmate',
};
const themeLabel = t => THEME_LABELS[t] || t;

/* =====================================================================
   WEAKNESS DASHBOARD
   Charts are single-series magnitude comparisons, so: one hue drawn from the
   app's own theme tokens (no categorical palette, no rainbow), a recessive
   grid, and a direct value label on each bar rather than an axis to read off.
   ===================================================================== */

function coachDashHTML(){
  const p = COACH_PROFILE;
  if(!p) return '';
  const r = p.rating||{}, e = p.errors||{}, rec = p.record||{};
  const games = p.gamesAnalysed||0;

  const tiles = [
    {v: r.current ?? '—', l:'chess.com rating',
     s: r.trend!=null ? `${r.trend>0?'+':''}${r.trend} over the sample` : `${games} games analysed`},
    {v: p.acpl ?? '—', l:'avg centipawn loss',
     s: acplVerdict(p.acpl)},
    {v: e.blunders_per_game ?? '—', l:'blunders per game',
     s: `${e.blunders||0} in ${games} games`},
    {v: rec.win!=null ? `${rec.win}/${rec.win+rec.loss+rec.draw}` : '—', l:'games won',
     s: `${rec.win||0}W ${rec.loss||0}L ${rec.draw||0}D`},
  ];
  let html = `<div class="coach-tiles">` + tiles.map(t=>
    `<div class="ctile"><b>${t.v}</b><span>${t.l}</span><small>${t.s}</small></div>`).join('') + `</div>`;

  // ---- top leaks: horizontal bars, one hue, value labelled at the end ----
  const w = (p.weaknesses||[]).slice(0,6);
  if(w.length){
    const max = Math.max(...w.map(x=>x.share));
    html += `<h3 class="coach-h">Where your points go</h3>
      <p class="coach-note">Share of everything you lost to serious errors, by pattern.
      This is what your practice is aimed at.</p>
      <div class="hbars">` + w.map(x=>`
        <div class="hbar" title="${x.count} serious errors · ${x.cp_lost} centipawns lost">
          <span class="hb-lab">${x.label}</span>
          <span class="hb-track"><i style="width:${Math.max(3,x.share/max*100)}%"></i></span>
          <span class="hb-val">${x.share}%</span>
        </div>`).join('') + `</div>`;
  }

  // ---- phase ----
  const ph = p.byPhase||{};
  const phases = ['opening','middlegame','endgame'].map(k=>({k, ...(ph[k]||{count:0,cp_lost:0})}));
  const phMax = Math.max(1,...phases.map(x=>x.cp_lost));
  html += `<h3 class="coach-h">When you go wrong</h3>
    <div class="hbars">` + phases.map(x=>`
      <div class="hbar">
        <span class="hb-lab">${x.k}</span>
        <span class="hb-track"><i style="width:${Math.max(2,x.cp_lost/phMax*100)}%"></i></span>
        <span class="hb-val">${x.count}</span>
      </div>`).join('') + `</div>`;

  // ---- clock pressure: same form, worst bucket flagged with a word, not
  //      colour alone, so it reads without relying on hue ----
  const tp = p.timePressure||{};
  const order = ['under 10%','10-25%','25-50%','over 50%'];
  const rows = order.filter(k=>tp[k] && tp[k].flagged_moves>=3).map(k=>({k, ...tp[k]}));
  if(rows.length>=2){
    const worst = rows.reduce((a,b)=>b.blunder_share>a.blunder_share?b:a);
    html += `<h3 class="coach-h">Clock pressure</h3>
      <p class="coach-note">Of your flagged moves, the share that were outright blunders —
      grouped by how much of your clock was left.</p>
      <div class="hbars">` + rows.map(x=>`
        <div class="hbar${x===worst?' worst':''}">
          <span class="hb-lab">${x.k} left</span>
          <span class="hb-track"><i style="width:${Math.max(2,x.blunder_share)}%"></i></span>
          <span class="hb-val">${x.blunder_share}%${x===worst?' <em>worst</em>':''}</span>
        </div>`).join('') + `</div>`;
    if(worst.k==='under 10%' || worst.k==='10-25%'){
      html += `<p class="coach-verdict">⏱ Your blunder rate roughly
        ${Math.round(worst.blunder_share/Math.max(1,rows[rows.length-1].blunder_share))}× when the clock
        gets low. Playing a slower time control is worth more rating than any puzzle set.</p>`;
    }
  }

  // ---- conversion & punishing ----
  const pu = p.punishing||{}, cv = p.conversion||{};
  const notes = [];
  if(pu.opponent_blunders) notes.push(`Your opponents blundered <b>${pu.opponent_blunders}</b> times and you
     converted <b>${pu.conversion_rate}%</b> of those chances.`);
  if(cv.was_winning_but_did_not_win) notes.push(`<b>${cv.was_winning_but_did_not_win}</b> games you were clearly
     winning and did not win.`);
  if(notes.length) html += `<h3 class="coach-h">Converting</h3>
    <p class="coach-note">${notes.join(' ')}</p>`;

  // ---- openings actually met ----
  const op = (p.openings&&p.openings.most_faced)||[];
  if(op.length){
    html += `<h3 class="coach-h">Openings you actually meet</h3>
      <p class="coach-note">Straight from your games — useful for deciding which lines in your
      repertoire are worth the time.</p>
      <table class="coach-table"><thead><tr><th>Opening</th><th>Games</th><th>Won</th><th>Leave book</th></tr></thead><tbody>`
      + op.slice(0,6).map(o=>`<tr><td>${o.opening}</td><td>${o.games}</td><td>${o.win_rate}%</td>
        <td>${o.avg_book_exit_move?('move '+o.avg_book_exit_move):'—'}</td></tr>`).join('')
      + `</tbody></table>`;
  }

  html += `<p class="coach-foot">Built from your last ${games} chess.com games ·
    generated ${EXDATA.generated}. Re-run <code>build/refresh.sh</code> to update.</p>`;
  return html;
}

function acplVerdict(a){
  if(a==null) return '';
  if(a<30) return 'very accurate';
  if(a<50) return 'strong';
  if(a<80) return 'typical club level';
  if(a<120) return 'lots of room to gain';
  return 'accuracy is your biggest lever';
}

/* ---------------- home-screen section ---------------- */
function renderTacticsSection(host){
  if(!hasCoach()) return;
  const wrap = document.createElement('div');
  wrap.innerHTML = `<h2 class="section-title">Your weaknesses
    <button id="coachBtn" class="link-btn">see the full report ›</button></h2>`;
  const grid = document.createElement('div');
  grid.className = 'course-grid';
  for(const pack of PACKS){
    const list = PUZZLES_BY_PACK[pack.id];
    if(!list.length) continue;
    const done = list.filter(c=>cardState(c.id)!=='new').length;
    const due  = list.filter(c=>cardState(c.id)==='due').length;
    const pct  = Math.round(list.reduce((s,c)=>s+cardStrength(c.id),0)/list.length*100);
    const card = document.createElement('div');
    card.className = 'course-card puzzle-card';
    card.innerHTML = `
      <div class="cc-top">
        <span class="tag ${packTagClass(pack.kind)}">${packTagLabel(pack.kind)}</span>
        ${due?`<span class="due-pill">${due} due</span>`
             :`<span class="due-pill none">${done<list.length?'practise':'✓'}</span>`}
      </div>
      <h3>${pack.name}</h3>
      <div class="cc-bar"><div style="width:${pct}%"></div></div>
      <div class="cc-meta"><span>${done}/${list.length} seen</span></div>`;
    card.addEventListener('click',()=>go('pack',pack.id));
    grid.appendChild(card);
  }
  wrap.appendChild(grid);
  // sits between the openings and the badge row, not after everything
  const badges = host.querySelector('.badge-row');
  if(badges) host.insertBefore(wrap, badges); else host.appendChild(wrap);
  const btn = wrap.querySelector('#coachBtn');
  if(btn) btn.addEventListener('click', e=>{ e.stopPropagation(); go('coach'); });
}
function packTagClass(kind){
  return kind==='own'||kind==='refute' ? 'black' : kind==='calc' ? 'calc' : 'white';
}
function packTagLabel(kind){
  return {own:'⚑ your games', punish:'⚑ your games', refute:'⚑ your games',
          calc:'🧠 calculation', endgame:'♔ endgame', theme:'⚔ drill'}[kind] || '⚔ drill';
}

/* ---------------- views ---------------- */
function renderCoach(){
  app.appendChild(tpl('tpl-coach'));
  $('#coachBody').innerHTML = coachDashHTML() ||
    '<p class="muted">No game analysis yet. Run <code>build/refresh.sh</code>.</p>';
}

function renderPack(packId){
  const pack = packById(packId);
  if(!pack) return go('home');
  app.appendChild(tpl('tpl-course'));
  $('#cdName').textContent = pack.name;
  $('#cdSummary').textContent = pack.blurb || '';
  const drill = $('#cdDrill');
  drill.textContent = '▶ Practise this set';
  drill.addEventListener('click',()=>{
    const q = PUZZLES_BY_PACK[packId].slice();
    beginSession(q,'pack',false);
  });
  const learn = $('#cdLearn');
  learn.textContent = '↻ Only what I got wrong';
  learn.addEventListener('click',()=>{
    const q = PUZZLES_BY_PACK[packId].filter(c=>{
      const s = srs(c.id); return s && s.lapses>0;
    });
    if(!q.length){ toast('Nothing failed in this set yet.',''); return; }
    beginSession(q,'pack',false);
  });

  const wrap = $('#cdLines');
  PUZZLES_BY_PACK[packId].forEach((card,i)=>{
    const st = cardState(card.id);
    const lbl = {new:'Not tried',due:'Review due',learning:'Learning',mature:'Solid'}[st];
    const row = document.createElement('div'); row.className='cd-line';
    row.innerHTML = `<div class="cl-top">
        <span class="cl-name">${i+1}. ${card.name}</span>
        <span class="cl-state ${st}">${lbl}</span></div>
      <div class="cl-moves">${puzzleSubtitle(card)}</div>`;
    row.addEventListener('click',()=>beginSession([card],'line',false));
    wrap.appendChild(row);
  });
}


/* =====================================================================
   LESSON VIEWS
   ===================================================================== */

function renderLessonsSection(host){
  if(!hasLessons()) return;
  const wrap = document.createElement('div');
  const dueN = lessonsDue();
  wrap.innerHTML = `<h2 class="section-title">Your lessons
    <span class="muted" style="font-weight:400;font-size:.78rem;text-transform:none;
      letter-spacing:0">${dueN ? dueN + ' to work on today' : 'all caught up'}</span></h2>
    <p class="coach-note" style="margin:-4px 0 14px">What your mistakes have in common,
      and the habit that fixes each one. Two lessons a day, with new positions every
      time — not the same blunder on repeat.</p>`;
  const grid = document.createElement('div');
  grid.className = 'course-grid';
  for(const L of LESSONS.slice().sort((a,b)=>lessonPriority(b)-lessonPriority(a))){
    const p = lessonProgress(L);
    const st = lessonState(L.id);
    const stage = lessonStage(L);
    const card = document.createElement('div');
    card.className = 'course-card lesson-card' + (p.mastered ? ' mastered' : '');
    card.innerHTML = `
      <div class="cc-top">
        <span class="tag lesson">◈ lesson</span>
        ${p.mastered ? `<span class="due-pill none">✓ mastered</span>`
          : st === 'learning' ? `<span class="due-pill none">resting</span>`
          : `<span class="due-pill">${st === 'new' ? 'start' : 'due'}</span>`}
      </div>
      <h3>${L.title}</h3>
      <div class="cc-bar"><div style="width:${p.pct}%"></div></div>
      <div class="cc-meta">
        <span>${stage.name}</span>
        <span>${p.clean}/${p.target}</span>
      </div>`;
    card.addEventListener('click', () => go('lesson', L.id));
    grid.appendChild(card);
  }
  wrap.appendChild(grid);
  const badges = host.querySelector('.badge-row');
  if(badges) host.insertBefore(wrap, badges); else host.appendChild(wrap);
}

function renderLesson(id){
  const L = LESSON_BY_ID[id];
  if(!L) return go('home');
  app.appendChild(tpl('tpl-lesson'));
  const p = lessonProgress(L);
  const ev = L.evidence || {};

  $('#lsTitle').textContent = L.title;
  $('#lsDiag').textContent = L.diagnosis || '';

  $('#lsBody').innerHTML = `
    <div class="ls-block ls-principle">
      <span class="ls-lab">The idea</span>
      <p>${L.principle}</p>
    </div>
    <div class="ls-block ls-habit">
      <span class="ls-lab">At the board, ask yourself</span>
      <p>${L.habit}</p>
    </div>
    ${L.note ? `<p class="coach-note">${L.note}</p>` : ''}

    <h3 class="coach-h">The evidence</h3>
    <p class="coach-note">${ev.count || 0} mistakes across your games,
      ${ev.share || 0}% of everything you lost to serious errors.
      ${ev.newlyExplained != null && ev.newlyExplained < ev.count
        ? `${ev.newlyExplained} of them are not explained by any other lesson.` : ''}</p>
    <div class="ls-examples">
      ${(ev.examples || []).map(x => `
        <a class="ls-ex" href="${x.url}" target="_blank" rel="noopener">
          <span class="ls-ex-txt"><b>move ${x.moveNumber}</b> you played <code>${x.played}</code>, best was <code>${x.best}</code></span>
          <span class="ls-cost">${costLabel(x.cpLoss)}</span>
        </a>`).join('')}
    </div>

    <h3 class="coach-h">The ladder</h3>
    <p class="coach-note">You work at one level until you can do it, then move up.
      Positions come from a pool, so a repeat visit is new material.</p>
    <div class="ls-ladder">
      ${L.stages.map((st, i) => {
        const done = st.cardObjs.filter(c => cardState(c.id) !== 'new').length;
        const cls = i < p.rung ? 'done' : i === p.rung ? 'current' : 'locked';
        return `<div class="ls-rung ${cls}">
          <span class="ls-rung-n">${i < p.rung ? '✓' : i + 1}</span>
          <span class="ls-rung-name">${st.name}
            <small>${st.retires ? 'from your own games — retires once solved'
                                : `${done}/${st.cardObjs.length} of the pool seen`}</small></span>
          ${i === p.rung ? `<span class="ls-rung-prog">${p.clean}/${p.target}</span>` : ''}
        </div>`;
      }).join('')}
    </div>`;

  const drill = $('#lsDrill');
  drill.textContent = p.mastered ? '↻ Keep it sharp' : '▶ Practise this lesson';
  drill.addEventListener('click', () => {
    const q = freshFromLesson(L, 6);
    if(!q.length){ toast('You have solved this whole pool — it will come back later.', ''); return; }
    beginSession(q, 'lesson', false);
  });
}
