/* =====================================================================
   Coach  --  tactics/calculation exercises built from your real games.

   Data comes from window.EXERCISES (generated by build/build_exercises.py
   out of your chess.com history). Everything here is optional: if
   exercises.js is missing the app runs exactly as it did before.

   A puzzle uses the SAME card shape as an opening line -- a start position
   plus a list of move-edges -- so the trainer engine in app.js plays both
   through one code path. The only additions are `startFen` (openings always
   began from the initial position) and `blind` (calculation mode).

   Loaded BEFORE app.js: it only defines things here, and is called later.
   ===================================================================== */
'use strict';

const EXDATA = window.EXERCISES || null;
const PACKS = EXDATA ? EXDATA.packs : [];
const COACH_PROFILE = EXDATA ? EXDATA.profile : null;

/* ---------------- puzzle cards ---------------- */
const PUZZLES = [];
const PUZZLE_BY_ID = {};
const PUZZLES_BY_PACK = {};
(function enumeratePuzzles(){
  for(const pack of PACKS){
    PUZZLES_BY_PACK[pack.id] = [];
    for(const item of pack.items){
      const card = {
        id: `${pack.id}#${item.id}`,
        isPuzzle: true,
        packId: pack.id,
        courseName: pack.name,
        name: (item.meta && item.meta.title) || pack.name,
        color: item.color,
        startFen: item.startFen,
        edges: item.edges,
        myMoves: item.myMoves,
        blind: !!pack.blind,
        meta: item.meta || {},
      };
      PUZZLES.push(card);
      PUZZLE_BY_ID[card.id] = card;
      PUZZLES_BY_PACK[pack.id].push(card);
    }
  }
})();
const packById = id => PACKS.find(p => p.id === id);
const hasCoach = () => PUZZLES.length > 0;

/* ---------------- adaptive difficulty ----------------
   Puzzles are bundled across a wide rating band and the app picks within it,
   so a bad initial guess at your level corrects itself in a few sessions
   instead of needing the whole set rebuilt. Standard Elo both ways: you rate
   the puzzle, the puzzle rates you. */
function puzzleRating(){
  if(state.profile.puzzleRating) return state.profile.puzzleRating;
  const band = COACH_PROFILE && COACH_PROFILE.puzzleBand;
  return (band && band.centre) || 900;
}
function updatePuzzleRating(card, solvedClean){
  const target = card.meta && card.meta.rating;
  if(!target) return;                       // own-game cards carry no rating
  const mine = puzzleRating();
  const expected = 1/(1+Math.pow(10,(target-mine)/400));
  const K = state.profile.puzzlesDone < 30 ? 40 : 20;   // settle in faster at first
  state.profile.puzzleRating = Math.round(mine + K*((solvedClean?1:0)-expected));
  state.profile.puzzlesDone = (state.profile.puzzlesDone||0)+1;
}

/* ---------------- daily tactics queue ----------------
   Reviews first (they are the ones at risk of being forgotten), then new
   puzzles chosen closest to your current level, spread across packs so a
   single theme never fills the whole session. */
function buildTacticsQueue(budget){
  if(budget<=0 || !hasCoach()) return [];
  const due = PUZZLES.filter(c=>cardState(c.id)==='due')
                     .sort((a,b)=>srs(a.id).due-srs(b.id).due);
  const out = due.slice(0,budget);
  let room = budget-out.length;
  if(room<=0) return out;

  const mine = puzzleRating();
  const fresh = PUZZLES.filter(c=>cardState(c.id)==='new');
  // Your own mistakes come first -- they are the highest-signal material and
  // there are only ever a few dozen of them.
  const own = fresh.filter(c=>c.meta.source!=='lichess');
  const rest = fresh.filter(c=>c.meta.source==='lichess')
                    .sort((a,b)=>Math.abs((a.meta.rating||mine)-mine)
                                -Math.abs((b.meta.rating||mine)-mine));
  const pool = own.concat(rest);

  // round-robin across packs so one theme can't monopolise the session
  const byPack = {};
  for(const c of pool){ (byPack[c.packId]=byPack[c.packId]||[]).push(c); }
  const keys = Object.keys(byPack);
  let i=0;
  while(room>0 && keys.some(k=>byPack[k].length)){
    const k = keys[i++ % keys.length];
    if(byPack[k].length){ out.push(byPack[k].shift()); room--; }
  }
  return out;
}

function tacticsDue(){ return PUZZLES.filter(c=>cardState(c.id)==='due').length; }
function tacticsNew(){ return PUZZLES.filter(c=>cardState(c.id)==='new').length; }
function tacticsSolved(){ return PUZZLES.filter(c=>cardState(c.id)!=='new').length; }

/* ---------------- per-card context shown during training ---------------- */
// Evaluations are clamped at ±10 pawns before differencing, so the worst
// mistakes all come out at exactly "20 pawns" — a number that means "winning
// to losing", not a literal material count. Say that instead of printing it.
function lossPhrase(cp){
  if(cp>=1500) return 'it threw the game away';
  if(cp>=900)  return 'it turned a winning position into a losing one';
  if(cp>=400)  return `it cost you about ${Math.round(cp/100)} pawns`;
  return `it cost you about ${(cp/100).toFixed(1)} pawns`;
}

function puzzlePrompt(card){
  const m = card.meta||{};
  switch(m.kind){
    case 'own':    return `You played ${m.played} here and ${lossPhrase(m.cpLoss)}. Find the move you missed.`;
    case 'punish': return `Your opponent just played ${m.oppMove}. Punish it.`;
    case 'refute': return `You just played ${m.played}. Now play your opponent's side and show why it loses.`;
    case 'calc':   return `Calculate the whole line before you move — the board will not update.`;
    case 'endgame':return `Find the winning technique.`;
    default:       return `Find the best move.`;
  }
}
function puzzleSubtitle(card){
  const m = card.meta||{};
  const bits = [];
  if(m.rating) bits.push(`rated ${m.rating}`);
  if(m.moveNumber) bits.push(`move ${m.moveNumber}`);
  if(m.timeClass) bits.push(m.timeClass);
  if(m.endTime) bits.push(new Date(m.endTime*1000).toLocaleDateString());
  if(m.themes && m.themes.length) bits.push(m.themes.slice(0,3).map(themeLabel).join(', '));
  return bits.join(' · ');
}
const THEME_LABELS = {
  hangingPiece:'hanging piece', fork:'fork', pin:'pin', skewer:'skewer',
  discoveredAttack:'discovered attack', backRankMate:'back rank',
  mateIn1:'mate in 1', mateIn2:'mate in 2', mateIn3:'mate in 3',
  trappedPiece:'trapped piece', promotion:'promotion',
  capturingDefender:'removing the defender', advancedPawn:'passed pawn',
  crushing:'winning material', advantage:'advantage', short:'short', long:'long',
  sacrifice:'sacrifice', deflection:'deflection', attraction:'attraction',
  quietMove:'quiet move', defensiveMove:'defensive move', intermezzo:'in-between move',
  doubleCheck:'double check', xRayAttack:'x-ray', interference:'interference',
  clearance:'clearance', zugzwang:'zugzwang', mate:'checkmate',
};
const themeLabel = t => THEME_LABELS[t] || t;

/* =====================================================================
   WEAKNESS DASHBOARD
   Charts are single-series magnitude comparisons, so: one hue drawn from the
   app's own theme tokens (no categorical palette, no rainbow), a recessive
   grid, and a direct value label on each bar rather than an axis to read off.
   ===================================================================== */

function coachDashHTML(){
  const p = COACH_PROFILE;
  if(!p) return '';
  const r = p.rating||{}, e = p.errors||{}, rec = p.record||{};
  const games = p.gamesAnalysed||0;

  const tiles = [
    {v: r.current ?? '—', l:'chess.com rating',
     s: r.trend!=null ? `${r.trend>0?'+':''}${r.trend} over the sample` : `${games} games analysed`},
    {v: p.acpl ?? '—', l:'avg centipawn loss',
     s: acplVerdict(p.acpl)},
    {v: e.blunders_per_game ?? '—', l:'blunders per game',
     s: `${e.blunders||0} in ${games} games`},
    {v: rec.win!=null ? `${rec.win}/${rec.win+rec.loss+rec.draw}` : '—', l:'games won',
     s: `${rec.win||0}W ${rec.loss||0}L ${rec.draw||0}D`},
  ];
  let html = `<div class="coach-tiles">` + tiles.map(t=>
    `<div class="ctile"><b>${t.v}</b><span>${t.l}</span><small>${t.s}</small></div>`).join('') + `</div>`;

  // ---- top leaks: horizontal bars, one hue, value labelled at the end ----
  const w = (p.weaknesses||[]).slice(0,6);
  if(w.length){
    const max = Math.max(...w.map(x=>x.share));
    html += `<h3 class="coach-h">Where your points go</h3>
      <p class="coach-note">Share of everything you lost to serious errors, by pattern.
      This is what your practice is aimed at.</p>
      <div class="hbars">` + w.map(x=>`
        <div class="hbar" title="${x.count} serious errors · ${x.cp_lost} centipawns lost">
          <span class="hb-lab">${x.label}</span>
          <span class="hb-track"><i style="width:${Math.max(3,x.share/max*100)}%"></i></span>
          <span class="hb-val">${x.share}%</span>
        </div>`).join('') + `</div>`;
  }

  // ---- phase ----
  const ph = p.byPhase||{};
  const phases = ['opening','middlegame','endgame'].map(k=>({k, ...(ph[k]||{count:0,cp_lost:0})}));
  const phMax = Math.max(1,...phases.map(x=>x.cp_lost));
  html += `<h3 class="coach-h">When you go wrong</h3>
    <div class="hbars">` + phases.map(x=>`
      <div class="hbar">
        <span class="hb-lab">${x.k}</span>
        <span class="hb-track"><i style="width:${Math.max(2,x.cp_lost/phMax*100)}%"></i></span>
        <span class="hb-val">${x.count}</span>
      </div>`).join('') + `</div>`;

  // ---- clock pressure: same form, worst bucket flagged with a word, not
  //      colour alone, so it reads without relying on hue ----
  const tp = p.timePressure||{};
  const order = ['under 10%','10-25%','25-50%','over 50%'];
  const rows = order.filter(k=>tp[k] && tp[k].flagged_moves>=3).map(k=>({k, ...tp[k]}));
  if(rows.length>=2){
    const worst = rows.reduce((a,b)=>b.blunder_share>a.blunder_share?b:a);
    html += `<h3 class="coach-h">Clock pressure</h3>
      <p class="coach-note">Of your flagged moves, the share that were outright blunders —
      grouped by how much of your clock was left.</p>
      <div class="hbars">` + rows.map(x=>`
        <div class="hbar${x===worst?' worst':''}">
          <span class="hb-lab">${x.k} left</span>
          <span class="hb-track"><i style="width:${Math.max(2,x.blunder_share)}%"></i></span>
          <span class="hb-val">${x.blunder_share}%${x===worst?' <em>worst</em>':''}</span>
        </div>`).join('') + `</div>`;
    if(worst.k==='under 10%' || worst.k==='10-25%'){
      html += `<p class="coach-verdict">⏱ Your blunder rate roughly
        ${Math.round(worst.blunder_share/Math.max(1,rows[rows.length-1].blunder_share))}× when the clock
        gets low. Playing a slower time control is worth more rating than any puzzle set.</p>`;
    }
  }

  // ---- conversion & punishing ----
  const pu = p.punishing||{}, cv = p.conversion||{};
  const notes = [];
  if(pu.opponent_blunders) notes.push(`Your opponents blundered <b>${pu.opponent_blunders}</b> times and you
     converted <b>${pu.conversion_rate}%</b> of those chances.`);
  if(cv.was_winning_but_did_not_win) notes.push(`<b>${cv.was_winning_but_did_not_win}</b> games you were clearly
     winning and did not win.`);
  if(notes.length) html += `<h3 class="coach-h">Converting</h3>
    <p class="coach-note">${notes.join(' ')}</p>`;

  // ---- openings actually met ----
  const op = (p.openings&&p.openings.most_faced)||[];
  if(op.length){
    html += `<h3 class="coach-h">Openings you actually meet</h3>
      <p class="coach-note">Straight from your games — useful for deciding which lines in your
      repertoire are worth the time.</p>
      <table class="coach-table"><thead><tr><th>Opening</th><th>Games</th><th>Won</th><th>Leave book</th></tr></thead><tbody>`
      + op.slice(0,6).map(o=>`<tr><td>${o.opening}</td><td>${o.games}</td><td>${o.win_rate}%</td>
        <td>${o.avg_book_exit_move?('move '+o.avg_book_exit_move):'—'}</td></tr>`).join('')
      + `</tbody></table>`;
  }

  html += `<p class="coach-foot">Built from your last ${games} chess.com games ·
    generated ${EXDATA.generated}. Re-run <code>build/refresh.sh</code> to update.</p>`;
  return html;
}

function acplVerdict(a){
  if(a==null) return '';
  if(a<30) return 'very accurate';
  if(a<50) return 'strong';
  if(a<80) return 'typical club level';
  if(a<120) return 'lots of room to gain';
  return 'accuracy is your biggest lever';
}

/* ---------------- home-screen section ---------------- */
function renderTacticsSection(host){
  if(!hasCoach()) return;
  const wrap = document.createElement('div');
  wrap.innerHTML = `<h2 class="section-title">Your weaknesses
    <button id="coachBtn" class="link-btn">see the full report ›</button></h2>`;
  const grid = document.createElement('div');
  grid.className = 'course-grid';
  for(const pack of PACKS){
    const list = PUZZLES_BY_PACK[pack.id];
    if(!list.length) continue;
    const done = list.filter(c=>cardState(c.id)!=='new').length;
    const due  = list.filter(c=>cardState(c.id)==='due').length;
    const pct  = Math.round(list.reduce((s,c)=>s+cardStrength(c.id),0)/list.length*100);
    const card = document.createElement('div');
    card.className = 'course-card puzzle-card';
    card.innerHTML = `
      <div class="cc-top">
        <span class="tag ${packTagClass(pack.kind)}">${packTagLabel(pack.kind)}</span>
        ${due?`<span class="due-pill">${due} due</span>`
             :`<span class="due-pill none">${done<list.length?'practise':'✓'}</span>`}
      </div>
      <h3>${pack.name}</h3>
      <div class="cc-bar"><div style="width:${pct}%"></div></div>
      <div class="cc-meta"><span>${done}/${list.length} seen</span></div>`;
    card.addEventListener('click',()=>go('pack',pack.id));
    grid.appendChild(card);
  }
  wrap.appendChild(grid);
  // sits between the openings and the badge row, not after everything
  const badges = host.querySelector('.badge-row');
  if(badges) host.insertBefore(wrap, badges); else host.appendChild(wrap);
  const btn = wrap.querySelector('#coachBtn');
  if(btn) btn.addEventListener('click', e=>{ e.stopPropagation(); go('coach'); });
}
function packTagClass(kind){
  return kind==='own'||kind==='refute' ? 'black' : kind==='calc' ? 'calc' : 'white';
}
function packTagLabel(kind){
  return {own:'⚑ your games', punish:'⚑ your games', refute:'⚑ your games',
          calc:'🧠 calculation', endgame:'♔ endgame', theme:'⚔ drill'}[kind] || '⚔ drill';
}

/* ---------------- views ---------------- */
function renderCoach(){
  app.appendChild(tpl('tpl-coach'));
  $('#coachBody').innerHTML = coachDashHTML() ||
    '<p class="muted">No game analysis yet. Run <code>build/refresh.sh</code>.</p>';
}

function renderPack(packId){
  const pack = packById(packId);
  if(!pack) return go('home');
  app.appendChild(tpl('tpl-course'));
  $('#cdName').textContent = pack.name;
  $('#cdSummary').textContent = pack.blurb || '';
  const drill = $('#cdDrill');
  drill.textContent = '▶ Practise this set';
  drill.addEventListener('click',()=>{
    const q = PUZZLES_BY_PACK[packId].slice();
    beginSession(q,'pack',false);
  });
  const learn = $('#cdLearn');
  learn.textContent = '↻ Only what I got wrong';
  learn.addEventListener('click',()=>{
    const q = PUZZLES_BY_PACK[packId].filter(c=>{
      const s = srs(c.id); return s && s.lapses>0;
    });
    if(!q.length){ toast('Nothing failed in this set yet.',''); return; }
    beginSession(q,'pack',false);
  });

  const wrap = $('#cdLines');
  PUZZLES_BY_PACK[packId].forEach((card,i)=>{
    const st = cardState(card.id);
    const lbl = {new:'Not tried',due:'Review due',learning:'Learning',mature:'Solid'}[st];
    const row = document.createElement('div'); row.className='cd-line';
    row.innerHTML = `<div class="cl-top">
        <span class="cl-name">${i+1}. ${card.name}</span>
        <span class="cl-state ${st}">${lbl}</span></div>
      <div class="cl-moves">${puzzleSubtitle(card)}</div>`;
    row.addEventListener('click',()=>beginSession([card],'line',false));
    wrap.appendChild(row);
  });
}
